#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


VER=4.3.0-040300
PREFIX=http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.3-unstable/
REL=201511020846
wget ${PREFIX}/linux-headers-${VER}-generic_${VER}.${REL}_amd64.deb
wget ${PREFIX}/linux-headers-${VER}_${VER}.${REL}_all.deb
wget ${PREFIX}/linux-image-${VER}-generic_${VER}.${REL}_amd64.deb
dpkg -i linux-*${VER}.${REL}*.deb
rm linux-*${VER}.${REL}*.deb
